// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace _30DaysAutomationChallenge.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("ToDoMvcFeature", Description="\tIn order to create and view Active/Completed/All tasks in the ToDoMvc AngularJSp" +
        "age\r\n\tAs a user\r\n\tI want to ensure the ToDOMVc page elements and task lists are " +
        "displayed correctly", SourceFile="Features\\ToDoMvcFeature.feature", SourceLine=0)]
    public partial class ToDoMvcFeatureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ToDoMvcFeature.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ToDoMvcFeature", "\tIn order to create and view Active/Completed/All tasks in the ToDoMvc AngularJSp" +
                    "age\r\n\tAs a user\r\n\tI want to ensure the ToDOMVc page elements and task lists are " +
                    "displayed correctly", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Verify Completed Lists", new string[] {
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=7)]
        public virtual void VerifyCompletedLists()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify Completed Lists", new string[] {
                        "Browser_Chrome",
                        "Browser_Firefox"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
testRunner.Given("I am on the ToDoMvc AngularJS Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Tasks"});
            table1.AddRow(new string[] {
                        "US Racing"});
            table1.AddRow(new string[] {
                        "Specflow"});
#line 10
testRunner.When("I Enter New tasks", ((string)(null)), table1, "When ");
#line 14
testRunner.And("I click on the checkbox of one of the tasks", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
testRunner.And("I Click on the Complete", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
testRunner.Then("all entered tasks are displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Verify Active Lists", new string[] {
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=19)]
        public virtual void VerifyActiveLists()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify Active Lists", new string[] {
                        "Browser_Chrome",
                        "Browser_Firefox"});
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
testRunner.Given("I am on the ToDoMvc AngularJS Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Tasks"});
            table2.AddRow(new string[] {
                        "30 days Challenge"});
            table2.AddRow(new string[] {
                        "Unit Tests"});
#line 22
testRunner.When("I Enter New tasks", ((string)(null)), table2, "When ");
#line 26
testRunner.And("I Click on the Active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
testRunner.Then("all entered tasks are displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Verify New Tasks", new string[] {
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=30)]
        public virtual void VerifyNewTasks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify New Tasks", new string[] {
                        "Browser_Chrome",
                        "Browser_Firefox"});
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
testRunner.Given("I am on the ToDoMvc AngularJS Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Tasks"});
            table3.AddRow(new string[] {
                        "SIS Greyhounds"});
            table3.AddRow(new string[] {
                        "SIS Throughbreds"});
#line 33
testRunner.When("I Enter New tasks", ((string)(null)), table3, "When ");
#line 37
testRunner.Then("all entered tasks are displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Verify All Lists", new string[] {
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=40)]
        public virtual void VerifyAllLists()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify All Lists", new string[] {
                        "Browser_Chrome",
                        "Browser_Firefox"});
#line 41
this.ScenarioSetup(scenarioInfo);
#line 42
testRunner.Given("I am on the ToDoMvc AngularJS Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Tasks"});
            table4.AddRow(new string[] {
                        "Automation"});
            table4.AddRow(new string[] {
                        "Atlas"});
#line 43
testRunner.When("I Enter New tasks", ((string)(null)), table4, "When ");
#line 47
testRunner.And("I click on the checkbox of one of the tasks", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
testRunner.And("I Click on the All", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
testRunner.Then("all entered tasks are displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Verify Clearing Completed Tasks", new string[] {
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=52)]
        public virtual void VerifyClearingCompletedTasks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify Clearing Completed Tasks", new string[] {
                        "Browser_Chrome",
                        "Browser_Firefox"});
#line 53
this.ScenarioSetup(scenarioInfo);
#line 54
testRunner.Given("I am on the ToDoMvc AngularJS Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Tasks"});
            table5.AddRow(new string[] {
                        "Betradar"});
            table5.AddRow(new string[] {
                        "Sporting Solutions"});
#line 55
testRunner.When("I Enter New tasks", ((string)(null)), table5, "When ");
#line 59
testRunner.And("I Click on Checkbox of \'Betradar\' one of Active tasks", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
testRunner.And("I Click on the Complete", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
testRunner.And("I click on the checkbox \'Betradar\' one of the Completed tasks", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
testRunner.And("I Click on the ClearCompleted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
testRunner.And("I Click on the All", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
testRunner.Then("only \'Sporting Solutions\' is displayed in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
